/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.example;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.geom.AffineTransform;
import java.util.ArrayList;
import javax.swing.JPanel;

/**
 *
 * @author User
 */
public class Fractal extends JPanel {

    private ArrayList<Shape> shapes;
    private double scale = 1;
    private int depth = 0;
    private double angle = 0;
    private int branches = 1;
    private double branchOffset = 0;
    
    private String rectFractal = "None";
    private String polylineFractal = "None";
    private String triFractal = "None";
    
    /**
     * Creates new form Fractal
     */
    public Fractal() {
        shapes = new ArrayList<>();
        initComponents();
        
    }
    
    public void setRectFractal(String rectFractal){
        this.rectFractal = rectFractal;
    }
    
    public void setTriFractal(String triFractal){
        this.triFractal = triFractal;
    }
    
    public void setPolylineFractal(String polylineFractal){
        this.polylineFractal = polylineFractal;
    }   
    
    
    /**
     * Recursively draws Sierpinski carpet, generated by dividing rectangles into 3x3 and removing the center rectangle
     * @param g2d
     * @param depth
     * @param rectangle 
     */
    private void drawSierpinskiCarpet(Graphics2D g2d, int depth, Rectangle rectangle) {

        double x = rectangle.getTopLeftX();
        double y = rectangle.getTopLeftY();
        double width = rectangle.getWidth();
        double height = rectangle.getHeight();

        //base case
        if (depth == 0) {
            g2d.fillRect((int)x,(int)y,(int)width,(int)height);
            return;
        }

        //calculate scaled dimensions
        double newWidth = width / 3 * scale;
        double newHeight = height / 3 * scale;

        //save original transform
        AffineTransform original = g2d.getTransform();

        //3x3 loop
        for (int r = 0; r < 3; r++) {
            for (int c = 0; c < 3; c++) {
                //skip center rectangle
                if (r == 1 && c == 1) {
                    continue;
                }

                //position of sub rectangle
                double newX = x + c * newWidth;
                double newY = y + r * newHeight;

                //branch offset
                if (branchOffset != 0) {
                    newX += branchOffset * (c - 1);
                    newY += branchOffset * (r - 1);
                }

                //create transformed rectangles
                Rectangle transformedRectangle = new Rectangle(
                    new Point(newX, newY),
                    (int) newWidth,
                    (int) newHeight
                );

                //rotation
                g2d.translate(newX + newWidth / 2, newY + newHeight / 2); //translate midpoint
                g2d.rotate(angle); //apply rotation
                g2d.translate(-(newX + newWidth / 2), -(newY + newHeight / 2)); //translate back

                //recursively draw
                drawSierpinskiCarpet(g2d, depth - 1, transformedRectangle);

                //return to old transformation
                g2d.setTransform(original);
            }
        }
    }
    
    /**
     * Recursively draws a T-square fractal, a pattern where smaller squares are generated at the corners of the current rectangle
     * @param g2d
     * @param depth
     * @param rectangle 
     */
    private void drawTSquare(Graphics2D g2d, int depth, Rectangle rectangle) {
        
        double width = rectangle.getWidth();
        double height = rectangle.getHeight();
        double x = rectangle.getTopLeftX();
        double y = rectangle.getTopLeftY();
        
        if (depth == 0) {
            rectangle.paint(g2d);
            return;
        }

        //draw current rectangle
        rectangle.paint(g2d);

        //manually scale
        double newWidth = width * scale/2;
        double newHeight = height * scale/2;

        double overlapX = newWidth / 4;
        double overlapY = newHeight / 4;

        //store relative offsets
        //dx: negative for left squares, positive for right squares
        //dy: negative for upper squares, positive for lower squares
        double[] dx = {-newWidth + overlapX, width - overlapX, -newWidth + overlapX, width - overlapX};
        double[] dy = {-newHeight + overlapY, -newHeight + overlapY, height - overlapY, height - overlapY};

        //make 4 new squares
        for (int i = 0; i < 4; i++) {
            //positioning, calculated by adding offsets (dx and dy)
            double scaledX = x + dx[i];
            double scaledY = y + dy[i];

            //branch offset
            if (dx[i] > 0) {
                scaledX += branchOffset; //right
            } 
            else {
                scaledX -= branchOffset; //left
            }
            if (dy[i] > 0) {
                scaledY += branchOffset; //downward
            } 
            else {
                scaledY -= branchOffset; //upward
            }

            //center of new squares
            double centerX = scaledX + newWidth / 2;
            double centerY = scaledY + newHeight / 2;
            
            //new rectangle
            Rectangle transformedRectangle = new Rectangle(new Point(scaledX, scaledY), (int)newWidth, (int) newHeight);

            //affinetransform to rotate
            AffineTransform original = g2d.getTransform();
            g2d.translate(centerX, centerY);  //translates from center
            g2d.rotate(angle);
            g2d.translate(-centerX, -centerY);

            //draws recursively
            drawTSquare(g2d, depth - 1, transformedRectangle);

            g2d.setTransform(original);
        }
    }

    
    /**
     * Recursively draws a spiral of rectangles by transforming and scaling the given rectangle, only achieved by scaling, translation and rotation
     * @param g2d
     * @param depth
     * @param rectangle 
     */
    private void drawRectangleSpiral(Graphics2D g2d, int depth, Rectangle rectangle){
        
        double cx = rectangle.getCenterX();
        double cy = rectangle.getCenterY();
        double width = rectangle.getWidth();
        double height = rectangle.getHeight();
        
        //base case
        if (depth == 0){
            rectangle.paint(g2d);
            return;
        }
        
        //top left corner is found by using scaling and branchoffset
        //cx and cy added in front to recenter
        double newX1 = cx + (rectangle.getTopLeftX() - cx) * scale + branchOffset * (depth - 1);
        double newY1 = cy + (rectangle.getTopLeftY() - cy) * scale + branchOffset * (depth - 1);
        
        //scaling 
        double newWidth = width*scale;
        double newHeight = height*scale;
        
        //new rectangle created to be called
        Rectangle transformedRectangle = new Rectangle(new Point(newX1, newY1), (int) newWidth, (int) newHeight);
        
        AffineTransform original = g2d.getTransform();
        
        g2d.translate(cx, cy);
        g2d.rotate(angle);
        g2d.translate(-cx, -cy);
        
        rectangle.paint(g2d);
        
        drawRectangleSpiral(g2d, depth-1,transformedRectangle);
        
        g2d.setTransform(original);
    }
    
    
    /**
     * Recursively draws the Sierpinski triangle fractal, generated by dividing current triangle into three smaller ones and recursively applying this process
     * @param g2d
     * @param depth
     * @param triangle 
     */
    private void drawSierpinskiTriangle(Graphics2D g2d, int depth, Triangle triangle){
        
        double cx = triangle.getCenterX();
        double cy = triangle.getCenterY();
        
        ArrayList<Point> vertices = triangle.getVertices();
        
        Point p1 = vertices.get(0);
        Point p2 = vertices.get(1);
        Point p3 = vertices.get(2);
        
        //base case
        if (depth == 0){
            triangle.paint(g2d);
            return;
        }
        
        //offsets are calculated for each vertex
        //move each vertex outward in direction relative to triangle's centroid
        double offsetX1 = branchOffset * (p1.getX() - cx) / triangle.getWidth();
        double offsetY1 = branchOffset * (p1.getY() - cy) / triangle.getHeight();

        double offsetX2 = branchOffset * (p2.getX() - cx) / triangle.getWidth();
        double offsetY2 = branchOffset * (p2.getY() - cy) / triangle.getHeight();

        double offsetX3 = branchOffset * (p3.getX() - cx) / triangle.getWidth();
        double offsetY3 = branchOffset * (p3.getY() - cy) / triangle.getHeight();
        
        //new points and scaling to store in new triangle array
        double newX1 = cx + (p1.getX() - cx) * scale + offsetX1;
        double newY1 = cy + (p1.getY() - cy) * scale + offsetY1;

        double newX2 = cx + (p2.getX() - cx) * scale + offsetX2;
        double newY2 = cy + (p2.getY() - cy) * scale + offsetY2;

        double newX3 = cx + (p3.getX() - cx) * scale + offsetX3;
        double newY3 = cy + (p3.getY() - cy) * scale + offsetY3;
        
        //transformations
        AffineTransform original = g2d.getTransform();
        g2d.translate(cx, cy);
        g2d.rotate(angle);
        g2d.translate(-cx,-cy);
        
        Triangle transformedTriangle = new Triangle(new Point(newX1, newY1), new Point(newX2, newY2),new Point(newX3, newY3));
        
        //new vertices array list
        ArrayList<Point> newVertices = transformedTriangle.getVertices();
        Point np1 = newVertices.get(0);
        Point np2 = newVertices.get(1);
        Point np3 = newVertices.get(2);
        
        //mid points for smaller triangles
        Point mid1 = new Point((np1.getX() + np2.getX()) / 2, (np1.getY() + np2.getY()) / 2);
        Point mid2 = new Point((np2.getX() + np3.getX()) / 2, (np2.getY() + np3.getY()) / 2);
        Point mid3 = new Point((np3.getX() + np1.getX()) / 2, (np3.getY() + np1.getY()) / 2);

        //3 smaller triangles
        Triangle t1 = new Triangle(np1, mid1, mid3);
        Triangle t2 = new Triangle(mid1, np2, mid2);
        Triangle t3 = new Triangle(mid3, mid2, np3);

        //paint the current triangle
        transformedTriangle.paint(g2d);

        //3 smaller triangles
        drawSierpinskiTriangle(g2d, depth - 1, t1);
        drawSierpinskiTriangle(g2d, depth - 1, t2);
        drawSierpinskiTriangle(g2d, depth - 1, t3);
            
        //restore transformation
        g2d.setTransform(original);
    }
    
    
    /**
     * Recursively draws a triangle spiral by transforming and scaling the given triangle, the spiral effect is only achieved by applying a scaling factor
     * @param g2d
     * @param depth
     * @param triangle 
     */
    private void drawTriangleSpiral(Graphics2D g2d, int depth, Triangle triangle) {
        
        double cx = triangle.getCenterX();
        double cy = triangle.getCenterY();
        
        ArrayList<Point> vertices = triangle.getVertices();

        Point p1 = vertices.get(0);
        Point p2 = vertices.get(1);
        Point p3 = vertices.get(2);
        
        if (depth == 0) {
            triangle.paint(g2d);
            return;
        }
        
        //new vertices
        //(x-cx) or (y-cy) computes distance p1 from centroid, and scale, and offset, centroid coord added to recenter
        double newX1 = cx + (p1.getX() - cx) * scale + branchOffset*(depth-1);
        double newY1 = cy + (p1.getY() - cy) * scale + branchOffset*(depth-1);

        double newX2 = cx + (p2.getX() - cx) * scale + branchOffset*(depth-1);
        double newY2 = cy + (p2.getY() - cy) * scale + branchOffset*(depth-1);

        double newX3 = cx + (p3.getX() - cx) * scale + branchOffset*(depth-1);
        double newY3 = cy + (p3.getY() - cy) * scale + branchOffset*(depth-1);
        
        Triangle transformedTriangle = new Triangle(new Point(newX1, newY1), new Point(newX2, newY2), new Point (newX3, newY3));

        AffineTransform original = g2d.getTransform();
        g2d.translate(cx, cy);
        g2d.rotate(angle);
        g2d.translate(-cx, -cy);
        
        //draw current triangle
        triangle.paint(g2d);
        
        //recursive method call
        drawTriangleSpiral(g2d, depth - 1, transformedTriangle);
        
        g2d.setTransform(original);

        
    }
    
    
    
    /**
     * Recursively draws the Koch curve for a given poly line, generated by subdividing each segment of the poly line into thirds, creating a triangular bump 
     * @param g2d
     * @param depth
     * @param polyline 
     */
    private void drawKoch(Graphics2D g2d, int depth, Polyline polyline) {
        
        ArrayList<Point> vertices = polyline.getVertices();
        ArrayList<Point> newVertices = new ArrayList<>();
        
        //base case
        if (depth == 0) {
            polyline.paint(g2d);
            return;
        }

        //loop through all points
        for (int i = 0; i < vertices.size() - 1; i++) {
            Point p1 = vertices.get(i);
            Point p2 = vertices.get(i + 1);

            //dividing segments by thirds
            double ax = p1.getX() + (p2.getX() - p1.getX()) / 3;
            double ay = p1.getY() + (p2.getY() - p1.getY()) / 3;

            double bx = p1.getX() + (p2.getX() - p1.getX()) * 2 / 3;
            double by = p1.getY() + (p2.getY() - p1.getY()) * 2 / 3;

            //mid point for bump point
            double mx = (ax + bx) / 2;
            double my = (ay + by) / 2;
            
            //length of segment
            double dx = bx - ax;
            double dy = by - ay;
            double length = Math.sqrt(Math.pow(dx,2) + Math.pow(dy,2));

            //height of bump including branchoffset, and separate coordinates of bump point
            double bumpHeight = length / 3 * scale + branchOffset;
            double px = mx - dy / length * bumpHeight;
            double py = my + dx / length * bumpHeight;
            
            //rotated bump point due to AffineTransform not working as intended for a fix
            double rotationX = px-mx;
            double rotationY = py-my;
            
            //2d rotational matrix
            double rotatedX = mx + rotationX * Math.cos(angle) - rotationY * Math.sin(angle);
            double rotatedY = my + rotationX * Math.sin(angle) + rotationY * Math.cos(angle);
            
            //rotation
            AffineTransform original = g2d.getTransform();
            g2d.translate((p1.getX() + p2.getX()) / 2, (p1.getY() + p2.getY()) / 2); //translate to midpoint
            g2d.rotate(angle); 
            g2d.translate(-(p1.getX() + p2.getX()) / 2, -(p1.getY() + p2.getY()) / 2); //translate back

            //transformed points
            newVertices.add(p1);
            newVertices.add(new Point(ax, ay)); //first third of the segment
            newVertices.add(new Point(rotatedX, rotatedY)); //bump
            newVertices.add(new Point(bx, by)); //last third of the segment

            g2d.setTransform(original); //restore original transform
        }

        newVertices.add(vertices.get(vertices.size() - 1)); //add last point

        //construct new polyline
        Polyline newPolyline = new Polyline(newVertices.get(0));
        for (int i = 1; i < newVertices.size(); i++) {
            newPolyline.addLast(newVertices.get(i));
        }

        //draw again
        drawKoch(g2d, depth - 1, newPolyline);
    }
  

    
    /**
     * Recursively draws the Levy C Curve for a given poly line, splits each segment of poly line and calculates a bend point
     * @param g2d
     * @param depth
     * @param polyline 
     */
    private void drawLevyCurve(Graphics2D g2d, int depth, Polyline polyline) {
        
        ArrayList<Point> vertices = polyline.getVertices();
        ArrayList<Point> newVertices = new ArrayList<>();
        
        //base case
        if (depth == 0) {
            polyline.paint(g2d);
            return;
        }
        
        //go through all points as it is a poly line
        for (int i = 0; i < vertices.size() - 1; i++) {
            Point p1 = vertices.get(i);
            Point p2 = vertices.get(i + 1);

            //mid points
            double mx = (p1.getX() + p2.getX()) / 2;
            double my = (p1.getY() + p2.getY()) / 2;

            //midpoint from bend and differences in x and y coordinates for p1 and p2
            double dx = p2.getX() - p1.getX();
            double dy = p2.getY() - p1.getY();
            double length = Math.sqrt(Math.pow(dx,2) + Math.pow(dy,2));

            //degenerate segments, if both points are the same, skip to avoid division by 0
            if (length == 0) {
                continue; 
            }
            
            //(-dy/length) and (dx/length) perpendicular direction
            //length/2 determines magnitude of offset
            //bend point rotated by angle
            double bendX = mx + (-dy / length * length / 2) * Math.cos(angle) - (dx / length * length / 2) * Math.sin(angle);
            double bendY = my + (-dy / length * length / 2) * Math.sin(angle) + (dx / length * length / 2) * Math.cos(angle);
            
            //branch offset
            bendX += branchOffset * (depth - 1);
            bendY += branchOffset * (depth - 1);

            //manual scaling to the bend point
            bendX = polyline.getCenterX() + (bendX - polyline.getCenterX()) * scale;
            bendY = polyline.getCenterY() + (bendY - polyline.getCenterY()) * scale;

            //add points for the new polyline
            newVertices.add(p1);
            //bending point
            newVertices.add(new Point(bendX, bendY)); 
        }

        //add the last point of the original polyline
        newVertices.add(vertices.get(vertices.size() - 1)); 

        //new polyline
        Polyline newPolyline = new Polyline(newVertices.get(0));
        for (int i = 1; i < newVertices.size(); i++) {
            newPolyline.addLast(newVertices.get(i));
        }

        //draw new polylines recursively
        drawLevyCurve(g2d, depth - 1, newPolyline);
    }

    
    //getters & setters
    public void setDepth(int depth){
        this.depth = depth;
        repaint();
    }
    
    public void setScale(double scale){
        this.scale = scale;
        repaint();
    }
    
    public void setAngle(double angle){
        this.angle = angle;
        repaint();
    }
    
    public void setBranchOffset(double branchOffset){
        this.branchOffset = branchOffset;
        repaint();
    }
    
    public void setBranch(int branches){
        this.branches = branches;
        repaint();
    }
    
    public ArrayList<Shape> getShapes(){
        return shapes;
    }
    
    public void setShapes(ArrayList<Shape> shapes){
        this.shapes = shapes;
    }
    
    /**
     * Pains the component and renders shape and their fractal variations, if applicable, provides custom rendering for shapes stored in array list
     * @param g 
     */
    @Override
    public void paintComponent(Graphics g){
        super.paintComponent(g);
        //if no shapes, nothing has to be drawn
        if(shapes == null || shapes.isEmpty()){
            return;
        }
        //draw with graphics2d to prevent pixelated lines
        Graphics2D g2d = (Graphics2D)g;
        g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING,RenderingHints.VALUE_ANTIALIAS_ON);
        
        
        //iterate through all shapes
        for(Shape s : shapes){
            g2d.setColor(s.getColor());
            switch (s) {
                case Polyline polyline -> {
                    switch(polylineFractal){
                        case "None" -> s.paint(g2d);
                        case "Koch Curve" -> drawKoch(g2d, depth, polyline);
                        case "Levy C Curve" -> drawLevyCurve(g2d, depth, polyline);
                    }
                }
                case Rectangle rectangle -> {
                    switch(rectFractal){
                        case "None" -> s.paint(g2d);
                        case "T-Square" -> drawTSquare(g2d, depth, rectangle);
                        case "Sierpinski" -> drawSierpinskiCarpet(g2d, depth, rectangle);
                        case "Spiral" -> drawRectangleSpiral(g2d, depth, rectangle);
                    }
                }
                case Triangle triangle -> {
                    switch(triFractal){
                        case "None" -> s.paint(g2d);
                        case "Sierpinski" -> drawSierpinskiTriangle(g2d, depth, triangle);
                        case "Spiral" -> drawTriangleSpiral(g2d, depth, triangle);
                    }
                }
                default -> {
                }
            }
        } 
    }
    


    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
