/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.example;

import java.util.ArrayList;
import javax.swing.JFrame;

/**
 *
 * @author ronni
 */
public class FractalGenerator extends JFrame {
    
    private ArrayList<Shape> shapes;

    /**
     * Constructs new instance of FractalGenerator, initializes new fractal object, retrieves list of shapes from fractal panel
     */
    public FractalGenerator() {
        fractal = new Fractal();
        shapes = fractal.getShapes();
        initComponents();
    }

    //getters & setters
    public Fractal getFractal(){
        return fractal;
    }
    
    public void setShapes(ArrayList<Shape> shapes){
        this.shapes = shapes;
        fractal.setShapes(shapes);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        settings = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        angleAdjuster = new javax.swing.JSlider();
        depthAdjuster = new javax.swing.JSlider();
        jLabel5 = new javax.swing.JLabel();
        scaleAdjuster = new javax.swing.JSlider();
        shapeButton = new javax.swing.JButton();
        branchOffsetAdjuster = new javax.swing.JSlider();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        polylineChoice = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        rectChoice = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        triChoice = new javax.swing.JComboBox<>();
        fractal = new org.example.Fractal();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(861, 500));

        settings.setBackground(new java.awt.Color(231, 231, 231));
        settings.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Fractal Generator");

        jLabel2.setText("Attributes");

        jLabel3.setText("Scale");

        jLabel4.setText("Depth");

        angleAdjuster.setMaximum(180);
        angleAdjuster.setMinimum(-180);
        angleAdjuster.setValue(0);
        angleAdjuster.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        angleAdjuster.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                angleAdjusterStateChanged(evt);
            }
        });

        depthAdjuster.setMaximum(10);
        depthAdjuster.setMinimum(0);
        depthAdjuster.setValue(0);
        depthAdjuster.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                depthAdjusterStateChanged(evt);
            }
        });

        jLabel5.setText("Angle");

        scaleAdjuster.setMaximum(200);
        scaleAdjuster.setValue(100);
        scaleAdjuster.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                scaleAdjusterStateChanged(evt);
            }
        });

        shapeButton.setText("Re-edit Shape");
        shapeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shapeButtonActionPerformed(evt);
            }
        });

        branchOffsetAdjuster.setMaximum(90);
        branchOffsetAdjuster.setMinimum(-90);
        branchOffsetAdjuster.setValue(0);
        branchOffsetAdjuster.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        branchOffsetAdjuster.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                branchOffsetAdjusterStateChanged(evt);
            }
        });

        jLabel9.setText("Offset");

        jLabel6.setText("Fractal Types");

        polylineChoice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Koch Curve", "Levy C Curve" }));
        polylineChoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                polylineChoiceActionPerformed(evt);
            }
        });

        jLabel8.setText("Polyline");

        jLabel10.setText("Rectangle");

        rectChoice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "T-Square", "Spiral", "Sierpinski" }));
        rectChoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rectChoiceActionPerformed(evt);
            }
        });

        jLabel11.setText("Triangle");

        triChoice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Sierpinski", "Spiral" }));
        triChoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                triChoiceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout settingsLayout = new javax.swing.GroupLayout(settings);
        settings.setLayout(settingsLayout);
        settingsLayout.setHorizontalGroup(
            settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(settingsLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(settingsLayout.createSequentialGroup()
                                .addGroup(settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(settingsLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(settingsLayout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(scaleAdjuster, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(settingsLayout.createSequentialGroup()
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(depthAdjuster, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(settingsLayout.createSequentialGroup()
                                                .addGap(41, 41, 41)
                                                .addComponent(angleAdjuster, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(settingsLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(settingsLayout.createSequentialGroup()
                                                .addGap(41, 41, 41)
                                                .addComponent(branchOffsetAdjuster, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addContainerGap(26, Short.MAX_VALUE))
                            .addGroup(settingsLayout.createSequentialGroup()
                                .addGroup(settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(settingsLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(settingsLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(polylineChoice, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(settingsLayout.createSequentialGroup()
                                                .addGroup(settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(rectChoice, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(settingsLayout.createSequentialGroup()
                                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(triChoice, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(0, 0, Short.MAX_VALUE))))))
            .addGroup(settingsLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(shapeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        settingsLayout.setVerticalGroup(
            settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(scaleAdjuster, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(depthAdjuster, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(angleAdjuster, javax.swing.GroupLayout.PREFERRED_SIZE, 17, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(branchOffsetAdjuster, javax.swing.GroupLayout.PREFERRED_SIZE, 17, Short.MAX_VALUE))
                .addGap(49, 49, 49)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(polylineChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(rectChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(triChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(shapeButton)
                .addGap(83, 83, 83))
        );

        fractal.setLayout(new java.awt.BorderLayout());
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(settings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(fractal, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(settings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(fractal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("Fractra");
        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Handles state change event for scaleAdjuster, updates scale value in fractal class
     * @param evt 
     */
    private void scaleAdjusterStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_scaleAdjusterStateChanged
        fractal.setScale(scaleAdjuster.getValue()/100.0);
    }//GEN-LAST:event_scaleAdjusterStateChanged

    /**
     * Handles state change event for depthAdjuster, updates depth value in fractal class
     * @param evt 
     */
    private void depthAdjusterStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_depthAdjusterStateChanged
        fractal.setDepth(depthAdjuster.getValue());
    }//GEN-LAST:event_depthAdjusterStateChanged

    /**
     * Handles state change event for angleAdjuster, updates angle value in fractal class
     * @param evt 
     */
    private void angleAdjusterStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_angleAdjusterStateChanged
        fractal.setAngle(Math.toRadians(angleAdjuster.getValue()));
    }//GEN-LAST:event_angleAdjusterStateChanged

    /**
     * Handles state change event for offsetAdjuster, updates offset value in fractal class
     * @param evt 
     */
    private void branchOffsetAdjusterStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_branchOffsetAdjusterStateChanged
        fractal.setBranchOffset(Math.toRadians(branchOffsetAdjuster.getValue()));
    }//GEN-LAST:event_branchOffsetAdjusterStateChanged

    /**
     * Handles action performed event for shapeButton, returns back to shape editor frame if pressed
     * @param evt 
     */
    private void shapeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shapeButtonActionPerformed
        ShapeEditor shapeEditor = new ShapeEditor();
        shapeEditor.getCanvas().getShapes().clear();
        shapeEditor.getCanvas().getShapes().addAll(fractal.getShapes()); //pass back 
        shapeEditor.getCanvas().repaint(); //redraw
        shapeEditor.setVisible(true);
        this.dispose(); //close fractalgenerator
    }//GEN-LAST:event_shapeButtonActionPerformed

    /**
     * Handles action performed event for poly line combo box, adjusts poly line fractal type 
     * @param evt 
     */
    private void polylineChoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_polylineChoiceActionPerformed
        fractal.setPolylineFractal((String)polylineChoice.getSelectedItem());
        fractal.repaint();
    }//GEN-LAST:event_polylineChoiceActionPerformed

    /**
     * Handles action performed for rectangle combo box, adjusts rectangle fractal type
     * @param evt 
     */
    private void rectChoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rectChoiceActionPerformed
        fractal.setRectFractal((String)rectChoice.getSelectedItem());
        fractal.repaint();
    }//GEN-LAST:event_rectChoiceActionPerformed

    /**
     * Handles action performed for triangle combo box, adjusts triangle fractal type
     * @param evt 
     */
    private void triChoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_triChoiceActionPerformed
        fractal.setTriFractal((String)triChoice.getSelectedItem());
        fractal.repaint();
    }//GEN-LAST:event_triChoiceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FractalGenerator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FractalGenerator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FractalGenerator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FractalGenerator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FractalGenerator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider angleAdjuster;
    private javax.swing.JSlider branchOffsetAdjuster;
    private javax.swing.JSlider depthAdjuster;
    private org.example.Fractal fractal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JComboBox<String> polylineChoice;
    private javax.swing.JComboBox<String> rectChoice;
    private javax.swing.JSlider scaleAdjuster;
    private javax.swing.JPanel settings;
    private javax.swing.JButton shapeButton;
    private javax.swing.JComboBox<String> triChoice;
    // End of variables declaration//GEN-END:variables
}
