/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.example;

import java.awt.Color;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import javax.swing.Timer;


/**
 *
 * @author ronni
 */
public class ShapeEditor extends javax.swing.JFrame {

    private String currentFilePath = null;
    private Timer overlapTimer;
    final static double LINE_PROXIMITY_THRESHOLD = 15;
    final static double POLYGON_PROXIMITY_THRESHOLD = 6; //for smoother dragging display and also due to more control on drag
    
    /**
     * Creates new form ShapeEditorFrame
     */
    public ShapeEditor() {
        initComponents();
        getRootPane().getInputMap().put(KeyStroke.getKeyStroke("ENTER"), "endPolyline");
        getRootPane().getActionMap().put("endPolyline", new KeyboardAction(this, "ENTER"));
        canvas.setFocusable(true);
        canvas.requestFocusInWindow();
        overlapError.setVisible(false);  
        finalizePolylineText.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        shapeButtonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        triangleButton = new javax.swing.JToggleButton();
        rectangleButton = new javax.swing.JToggleButton();
        lineButton = new javax.swing.JToggleButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 3), new java.awt.Dimension(0, 3), new java.awt.Dimension(32767, 3));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        jLabel4 = new javax.swing.JLabel();
        colorPanel = new javax.swing.JPanel();
        overlapError = new javax.swing.JLabel();
        generateButton = new javax.swing.JButton();
        finalizePolylineText = new javax.swing.JLabel();
        finalizePolylineText1 = new javax.swing.JLabel();
        canvas = new org.example.Canvas();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        openProject = new javax.swing.JMenuItem();
        saveProject = new javax.swing.JMenuItem();
        saveNewProject = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        deleteAll = new javax.swing.JMenuItem();
        deleteLast = new javax.swing.JMenuItem();

        shapeButtonGroup.add(lineButton);
        shapeButtonGroup.add(rectangleButton);
        shapeButtonGroup.add(triangleButton);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fractra");
        setPreferredSize(new java.awt.Dimension(861, 500));

        jPanel1.setBackground(new java.awt.Color(231, 231, 231));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setText("Shapes");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Shape Editor");

        triangleButton.setText("Triangle");
        triangleButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                triangleButtonMouseClicked(evt);
            }
        });

        rectangleButton.setText("Rectangle");
        rectangleButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rectangleButtonMouseClicked(evt);
            }
        });

        lineButton.setText("Polyline");
        lineButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lineButtonMouseClicked(evt);
            }
        });

        jLabel4.setText("Color Settings");

        colorPanel.setBackground(new java.awt.Color(0, 0, 0));
        colorPanel.setForeground(new java.awt.Color(255, 255, 255));
        colorPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        colorPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                colorPanelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout colorPanelLayout = new javax.swing.GroupLayout(colorPanel);
        colorPanel.setLayout(colorPanelLayout);
        colorPanelLayout.setHorizontalGroup(
            colorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 159, Short.MAX_VALUE)
        );
        colorPanelLayout.setVerticalGroup(
            colorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 92, Short.MAX_VALUE)
        );

        overlapError.setForeground(new java.awt.Color(255, 0, 0));
        overlapError.setText("Lines cannot overlap! ");

        generateButton.setText("Generate Fractal");
        generateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                generateButtonMouseClicked(evt);
            }
        });

        finalizePolylineText.setText("Press ENTER to finalize current polyline!");
        finalizePolylineText.setAlignmentX(2.5F);

        finalizePolylineText1.setForeground(new java.awt.Color(231, 231, 231));
        finalizePolylineText1.setText("Press ENTER to finalize current polyline!");
        finalizePolylineText1.setAlignmentX(2.5F);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(14, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(finalizePolylineText1)
                            .addComponent(finalizePolylineText)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lineButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(rectangleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(triangleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(generateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(overlapError))
                                    .addComponent(colorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lineButton)
                        .addGap(7, 7, 7)
                        .addComponent(rectangleButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(triangleButton)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(finalizePolylineText)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(finalizePolylineText1)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(colorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(overlapError, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(generateButton)
                .addGap(57, 57, 57))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.WEST);

        canvas.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                canvasMouseDragged(evt);
            }
        });
        canvas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                canvasMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                canvasMouseReleased(evt);
            }
        });
        canvas.setLayout(new java.awt.BorderLayout());
        getContentPane().add(canvas, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");

        openProject.setText("Open");
        openProject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                openProjectMousePressed(evt);
            }
        });
        jMenu1.add(openProject);

        saveProject.setText("Save");
        saveProject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                saveProjectMousePressed(evt);
            }
        });
        jMenu1.add(saveProject);

        saveNewProject.setText("Save As");
        saveNewProject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                saveNewProjectMousePressed(evt);
            }
        });
        jMenu1.add(saveNewProject);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        deleteAll.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_BACK_SPACE, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        deleteAll.setText("Delete All");
        deleteAll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                deleteAllMousePressed(evt);
            }
        });
        jMenu2.add(deleteAll);

        deleteLast.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_SUBTRACT, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        deleteLast.setText("Delete Last Shape");
        deleteLast.setToolTipText("");
        deleteLast.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                deleteLastMousePressed(evt);
            }
        });
        jMenu2.add(deleteLast);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Handles mouse click event on colorPanel, opens color chooser dialog to let user to select a new color
     * @param evt 
     */
    private void colorPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colorPanelMouseClicked
        Color newColor = JColorChooser.showDialog(this, "Color Selector", Color.BLACK);
        colorPanel.setBackground(newColor);
        canvas.setColor(newColor);
    }//GEN-LAST:event_colorPanelMouseClicked

    /**
     * Mouse click event on lineButton, sets next shape to be the line
     * @param evt 
     */
    private void lineButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lineButtonMouseClicked
        canvas.setNextShape(Canvas.LINE);
    }//GEN-LAST:event_lineButtonMouseClicked

    /**
     * Sets next shape to be a rectangle
     * @param evt 
     */
    private void rectangleButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rectangleButtonMouseClicked
        canvas.setNextShape(Canvas.RECT);
    }//GEN-LAST:event_rectangleButtonMouseClicked

    /**
     * Sets next shape to be triangle
     * @param evt 
     */
    private void triangleButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_triangleButtonMouseClicked
        canvas.setNextShape(Canvas.TRI);
    }//GEN-LAST:event_triangleButtonMouseClicked

    /**
     * Updates position of last shape being drawn based on current mouse location, if mouse is within snap threshold, it snaps to the closest vertex
     * Also updates rectangle and triangle while drawing
     * @param evt 
     */
    private void canvasMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canvasMouseDragged
        int x=evt.getX();
        int y=evt.getY();
        
        Shape last=canvas.getShapes().isEmpty()?null:canvas.getLastShape();
        
        //checks if point is snappable to the closest vertex
        Point mouse = new Point(x,y);
        Point snapPoint = canvas.snapToVertex(mouse, POLYGON_PROXIMITY_THRESHOLD);
              
        if (last instanceof Rectangle r) {
            r.setP2(snapPoint);
        }
        else if (last instanceof Triangle t){
            t.setP(snapPoint);
        }
        
        canvas.repaint();
    }//GEN-LAST:event_canvasMouseDragged

    /**
     * Processes user input to draw and edit shapes on canvas, including snapping, detecting overlaps, and adding new poly-lines or points
     * @param evt 
     */
    private void canvasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canvasMousePressed
        int x = evt.getX();
        int y = evt.getY();

        Shape last = canvas.getShapes().isEmpty()?null:canvas.getLastShape();
        
        //for snapping vertices
        Point mouse = new Point(x,y);
        Point snapPoint = canvas.snapToVertex(mouse, LINE_PROXIMITY_THRESHOLD);
        
        //if last edited/drawn shape was polyline
        if (last instanceof Polyline current) {

            //add new polyline if no incomplete polylines
            //this check is because the
            if (!current.isCompleted()) {
                //check for overlap
                if (current.hasOverlap(snapPoint, canvas)) {
                    showOverlapError();
                    return;
                }

                current.addLast(snapPoint);
            } 
            else {
                canvas.addNewShape(snapPoint.getX(), snapPoint.getY());  
            }
        } 
        //add new shape if there are no incomplete polylines
        else{
            canvas.addNewShape(snapPoint.getX(), snapPoint.getY());
        }
        canvas.repaint();
        showFinalizePolylineText();
        this.getRootPane().requestFocusInWindow();
    }//GEN-LAST:event_canvasMousePressed
  
    /**
     * Handles mouse click on generateButton, validates canvas and displays FractalGenerator if valid
     * @param evt 
     */
    private void generateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generateButtonMouseClicked
        if (validCanvas()){
            FractalGenerator fractalGen = new FractalGenerator();
            fractalGen.getFractal().setShapes(canvas.getShapes());
            fractalGen.setVisible(true);
            
            //close ShapeEditor frame
            this.dispose();
        }
    }//GEN-LAST:event_generateButtonMouseClicked

    /**
     * Handles mouse pressed event on deleteAll button, removes all shapes in shapes array list if confirms
     * @param evt 
     */
    private void deleteAllMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteAllMousePressed
        int select = JOptionPane.showConfirmDialog(this, "Are you sure you want to clear the canvas?");
        if (select == JOptionPane.YES_OPTION){
            canvas.removeAllShapes();
        }
    }//GEN-LAST:event_deleteAllMousePressed

    /**
     * Handles mouse pressed event on deleteLast button, and deletes the most recent shape if confirmed
     * @param evt 
     */
    private void deleteLastMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteLastMousePressed
        canvas.removeLast();
    }//GEN-LAST:event_deleteLastMousePressed

    /**
     * Handles mouse released event, checks if last drawn shape overlaps with any other shape, and if so, shape is removed from canvas and overlap error is shown
     * @param evt 
     */
    private void canvasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canvasMouseReleased
        Shape last = canvas.getShapes().isEmpty() ? null : canvas.getLastShape();

        //rectangle check
        if (last instanceof Rectangle rect) {
            //if the rectangle overlaps with any other shape
            if (rect.hasOverlap(new Point(), canvas)) {
                canvas.getShapes().remove(last);
                showOverlapError();
            }
        } 
        else if (last instanceof Triangle tri) {
            //if the triangle overlaps with any other shape
            if (tri.hasOverlap(new Point(), canvas)) {
                canvas.getShapes().remove(last);
                showOverlapError();
            }
        }
        canvas.repaint();
    }//GEN-LAST:event_canvasMouseReleased

    /**
     * Handles mouse pressed event on openProject, open file chooser to let user select project file, and loads shape from the file if the file is valid
     * @param evt 
     */
    private void openProjectMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openProjectMousePressed
        JFileChooser fc = new JFileChooser();
        fc.setDialogTitle("Open Project");
        int choice = fc.showOpenDialog(this);
        if (choice == JFileChooser.APPROVE_OPTION){
            File f = fc.getSelectedFile();
            ArrayList<Shape> shapes = ShapeIO.shapesFromFile(f.getAbsolutePath());
            if(shapes != null){
                canvas.setShapes(shapes);
                currentFilePath = f.getAbsolutePath();
            }
            else{
                JOptionPane.showMessageDialog(this, "Shapes cannot be loaded");
            }
        }
    }//GEN-LAST:event_openProjectMousePressed

    /**
     * Handles mouse pressed event on saveProject, and saves current canvas shapes to a file, if a file path is already specified, then the shapes are directly saved, if not, open file chooser to let user select or create file
     * @param evt 
     */
    private void saveProjectMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveProjectMousePressed
        if (currentFilePath != null){
            ShapeIO.shapesToFile(canvas.getShapes(),currentFilePath);
        }
        else{
            JFileChooser fc = new JFileChooser();
            fc.setDialogTitle("Save");
            int choice = fc.showSaveDialog(this);
            if(choice == JFileChooser.APPROVE_OPTION){
                File f = fc.getSelectedFile();
                currentFilePath = f.getAbsolutePath();
                ShapeIO.shapesToFile(canvas.getShapes(), currentFilePath);
            }
        }
    }//GEN-LAST:event_saveProjectMousePressed

    /**
     * Handles the mouse pressed event on saveNewProject, opens a file chooser dialog to allow user to specify a new file location for saving
     * @param evt 
     */
    private void saveNewProjectMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveNewProjectMousePressed
        JFileChooser fc = new JFileChooser();
        fc.setDialogTitle("Save As");
        int choice = fc.showSaveDialog(this);
        if(choice == JFileChooser.APPROVE_OPTION){
            File f = fc.getSelectedFile();
            currentFilePath = f.getAbsolutePath();
            ShapeIO.shapesToFile(canvas.getShapes(),currentFilePath);
        }
    }//GEN-LAST:event_saveNewProjectMousePressed

    /**
     * Finalizes current poly line being drawn on canvas after ENTER key press and confirm on dialog
     */
    public void finishCurrentPolyline() {
        Shape last = canvas.getShapes().isEmpty()?null:canvas.getLastShape();

        int select = JOptionPane.showConfirmDialog(this, "Do you want to finalize the current polyline?");
        if (select == JOptionPane.YES_OPTION && last instanceof Polyline){
            //finalize the current polyline
            Polyline current = (Polyline) last;

            current.setCompleted(true);  
            canvas.repaint();
            showFinalizePolylineText();
        
        }
    }
    
    /**
     * Displays an overlap error on the toolbar and hides it after 2 seconds, ensures any existing timers are stopped before creating a new one
     */
    private void showOverlapError(){
        overlapError.setVisible(true);
        
        //checks for and stops existing timers
        if (overlapTimer != null && overlapTimer.isRunning()) {
            overlapTimer.stop();
        }

        //create/reset timer
        overlapTimer = new Timer(2000, e -> {
            overlapError.setVisible(false);
            //repaint to ensure accurate display on gui
            canvas.repaint(); 
        });
        
        //no repeating
        overlapTimer.setRepeats(false);
        //start timer
        overlapTimer.start();       
    }
    
    /**
     * Update visibility of finalize poly line text based on canvas state
     */
    private void showFinalizePolylineText(){
        finalizePolylineText.setVisible(canvas.isDrawingPolyline());
    }
    
    /**
     * Validates canvas to ensure it is suitable for generating a fractal
     * @return true if canvas is valid for fractal generation, false otherwise
     */
    public boolean validCanvas(){
        for (Shape shape : canvas.getShapes()){
            if (shape instanceof Polyline l){
                if (!l.isCompleted()){
                    JOptionPane.showMessageDialog(this, "Cannot generate fractal with incomplete polylines.");
                    return false;
                }
            }
        }
        
        if (canvas.getShapes() == null || canvas.getShapes().isEmpty()){
            JOptionPane.showMessageDialog(this, "Cannot generate fractal with no shapes.");
            return false;
        }
        
        return true;
    }
    
    /**
     * Retrieves current canvas
     * @return canvas object on shape editor frame
     */
    public Canvas getCanvas(){
        return canvas;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShapeEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShapeEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShapeEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShapeEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShapeEditor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.example.Canvas canvas;
    private javax.swing.JPanel colorPanel;
    private javax.swing.JMenuItem deleteAll;
    private javax.swing.JMenuItem deleteLast;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JLabel finalizePolylineText;
    private javax.swing.JLabel finalizePolylineText1;
    private javax.swing.JButton generateButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton lineButton;
    private javax.swing.JMenuItem openProject;
    private javax.swing.JLabel overlapError;
    private javax.swing.JToggleButton rectangleButton;
    private javax.swing.JMenuItem saveNewProject;
    private javax.swing.JMenuItem saveProject;
    private javax.swing.ButtonGroup shapeButtonGroup;
    private javax.swing.JToggleButton triangleButton;
    // End of variables declaration//GEN-END:variables
}
